# Generated by Django 4.2.8 on 2026-06-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('timeframe', models.CharField(db_index=True, max_length=10)),
                ('time', models.DateTimeField(db_index=True)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-time'],
                'unique_together': {('symbol', 'timeframe', 'time')},
            },
        ),
    ]
